version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: "go.Dockerfile"
      target: dev
    environment:
      APP_PORT: 8080
      GIZLOG_ENV: dev
      GIZLOG_DB_HOST: db
      GIZLOG_DB_PORT: 3306
      GIZLOG_DB_NAME: gizlog
      GIZLOG_DB_USER: gizlog
      GIZLOG_DB_PASSWORD: secret
      TZ: "Asia/Tokyo"
    ports:
      - 9999:8080
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/arm64/v8
    ports:
      - 3305:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: gizlog
      MYSQL_USER: gizlog
      MYSQL_PASSWORD: secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

volumes:
  db: