version: "3.9"

services:
  user:
    container_name: gizlog
    build:
      context: .
      dockerfile: "go.Dockerfile"
      args:
        - target=dev
    entrypoint: ["./docker/entrypoint.sh", "./cmd/microservices/orders/main.go"]
    environment:
      GIZLOG_ENV: dev
      APP_PORT: 8080
      GIZLOG_DB_HOST: db
      GIZLOG_DB_PORT: 3306
      GIZLOG_DB_NAME: gizlog
      GIZLOG_DB_USER: gizlog
      GIZLOG_DB_PASSWORD: secret
    ports:
      - 9999:8080
    volumes:
      - .:/app
    tty: true
    depends_on:
      - db
  report:
    container_name: gizlog
    build:
      context: .
      dockerfile: "go.Dockerfile"
      args:
        - target=dev
    entrypoint: ["./docker/entrypoint.sh", "./cmd/microservices/orders/main.go"]
    environment:
      GIZLOG_ENV: dev
      APP_PORT: 8080
      GIZLOG_DB_HOST: db
      GIZLOG_DB_PORT: 3306
      GIZLOG_DB_NAME: gizlog
      GIZLOG_DB_USER: gizlog
      GIZLOG_DB_PASSWORD: secret
    ports:
      - 9999:8080
    volumes:
      - .:/app
    tty: true
    depends_on:
      - db
  question_board:
    container_name: gizlog
    build:
      context: .
      dockerfile: "go.Dockerfile"
      args:
        - target=dev
    entrypoint: ["./docker/entrypoint.sh", "./cmd/microservices/orders/main.go"]
    environment:
      GIZLOG_ENV: dev
      APP_PORT: 8080
      GIZLOG_DB_HOST: db
      GIZLOG_DB_PORT: 3306
      GIZLOG_DB_NAME: gizlog
      GIZLOG_DB_USER: gizlog
      GIZLOG_DB_PASSWORD: secret
    ports:
      - 9999:8080
    volumes:
      - .:/app
    tty: true
    depends_on:
      - db

  # rabbitmq:
  #   image: rabbitmq:3.7-management
  #   ports:
  #     - "15672:15672"

  db:
    container_name: gizlog-db
    image: mysql:8.0
    # M1 の人は platform をコメントイン
    # platform: linux/amd64
    ports:
      - 3308:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: gizlog
      MYSQL_USER: gizlog
      MYSQL_PASSWORD: gizlog
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

volumes:
  db:
    name: gizlog-db
